### ISSUE TITLE
nyx fails to build with Python 3.11.0a2

### ISSUE THREAD

**Issue by jorti** [torproject/nyx#49]
Hi,

Fedora is testing rebuilding its packages with Python 3.11, which is expected to be released in Fedora 37 (~ 1 year), and we have found this error when running the nyx tests.

See original bug report: https://bugzilla.redhat.com/show_bug.cgi?id=2021902

```
+ /usr/bin/python3 run_tests.py
Traceback (most recent call last):
  File "/builddir/build/BUILD/nyx-2.1.0/run_tests.py", line 80, in <module>
    main()
    ^^^^^^
  File "/usr/lib/python3.11/site-packages/stem/util/conf.py", line 288, in wrapped
    if 'config' in inspect.getargspec(func).args:
                   ^^^^^^^^^^^^^^^^^^
AttributeError: module 'inspect' has no attribute 'getargspec'. Did you mean: 'getargs'?
```

Removed from the inspect module:
- the `getargspec` function, deprecated since Python 3.0; use `inspect.signature()` or `inspect.getfullargspec()` instead.

https://bugs.python.org/issue45320
https://docs.python.org/3.11/whatsnew/3.11.html

**Comment by atagar** [comment]
Thanks Juan. I recently got another ticket about a Python 3.10+ compatibility issue.

https://github.com/torproject/stem/issues/109

It's a pity the PSF stopped obeying symantic versioning by breaking backward compatibility with minor version bumps.

**Comment by atagar** [comment]
Thanks Juan, patch merged.
